# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

ENV["RAILS_ENV"] ||= "cucumber"
require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')

require 'cucumber/formatter/unicode' # Remove this line if you don't want Cucumber Unicode support
require 'cucumber/rails/world'
#require 'cucumber/web/tableish' # Tableish is depricated now.
require 'factory_girl'
require File.expand_path('spec/factories')
require 'factory_girl/step_definitions'
require 'capybara/rails'
require 'capybara/cucumber'
require 'capybara/session'
require 'cucumber/rails'
require 'selenium-webdriver'
require 'email_spec'
require 'email_spec/cucumber'
require 'capybara/poltergeist'
require 'capybara-screenshot/cucumber'

Capybara.register_driver :poltergeist do |app|
  options = { :js_errors => false }
  Capybara::Poltergeist::Driver.new(app, options)
end


Capybara.default_selector = :css
#Capybara.server_boot_timeout = 50
Capybara.default_wait_time = 3
#Capybara.javascript_driver = :webkit
#Capybara.javascript_driver = :selenium
Capybara.javascript_driver = :poltergeist


if defined?(ActiveRecord::Base)
  begin
    require 'database_cleaner'
    DatabaseCleaner.strategy = :truncation
  rescue LoadError => ignore_if_database_cleaner_not_present
  end
end

WebMock.disable_net_connect!(:allow_localhost => true)
