default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: lz_dev
  host: localhost
  username: postgres
  password: postgres
test:
  <<: *default
  database: lz_test
  host: localhost
  username: postgres
  password: postgres
production:
  <<: *default
  database: linguazone_customizer_production
